name: Build and push a CRF-only docker image

on:
  workflow_dispatch:
    inputs:
      suffix:
        type: string
        description: Docker image suffix (e.g. develop, crf, full)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build -x test

  docker-build:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: Dockerfile.crf
          username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
          password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
          image: lfoppiano/grobid
          registry: docker.io
          pushImage: true
          tags:  |
            latest-develop, latest-crf${{ github.event.inputs.suffix != '' && '-' || '' }}${{ github.event.inputs.suffix }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
